# Generated by Django 3.2.9 on 2022-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from1', models.CharField(max_length=50)),
                ('to1', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
            ],
        ),
    ]
